name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Optional: enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: CW_final.tex  # Ensure this is the correct filename for your main .tex file

      - name: List Files for Debugging  # Optional step to confirm file presence
        run: ls -R

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: CW_final.pdf  # Confirm this matches the actual PDF output filename


